version: '3'

services:
  node:
    build: .
    networks:
      - krumiprog-net
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: on-failure

  postgres:
    build: ./database/
    networks:
      - krumiprog-net
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: on-failure

networks:
  krumiprog-net:
    driver: bridge
